name: Windows_Remote_VPS

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop & RDP
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo adduser xrdp ssl-cert
          echo "runneradmin:123456" | sudo chpasswd
          sudo service xrdp start
          
      - name: Setup Tunnel (Ngrok)
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok config add-authtoken YOUR_NGROK_TOKEN
          ngrok tcp 3389 --log=stdout > /dev/null &
          sleep 10
          echo "ADDRESS RDP:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
          
      - name: Keep Alive
        run: sleep 21600
